# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adfa68fef5c6eaf99bc047212ef2622ed5faa085873ac47dedadb2e6da4d02d47d3d7dd6a15d474d01bbae1f752ac998975532a38658a4b564d1859e3ee2d58c

test:
  secret_key_base: c82938732e91276964738afaeee1a9778f0b80b621427c5204ed2ac5c43c2ce5630cf7d1f43b3eb29f8a31c48f58ca3b4e8125043b584f40f40b4d0cb5656129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
